# Generated by Django 4.0.4 on 2022-09-13 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_goals', '0002_alter_goal_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.IntegerField(verbose_name='impact')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goals.goal', verbose_name='goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
