# Generated by Django 4.0.4 on 2022-09-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goals', '0004_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_done',
            field=models.BooleanField(default=False, null=True, verbose_name='done'),
        ),
    ]
