# Generated by Django 4.0.4 on 2022-08-23 15:03

import app_users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, default='profile_images/defaultuser.png', null=True, upload_to=app_users.models.user_directory_path, verbose_name='image')),
                ('profile_head_img', models.ImageField(blank=True, default='profile_images/defaulthead.png', null=True, upload_to=app_users.models.user_directory_path, verbose_name='head image')),
                ('is_banned', models.BooleanField(default=False, null=True, verbose_name='banned')),
                ('news_count', models.IntegerField(default=0, verbose_name='news_count')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='subscribers')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='subscriptions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
