# Generated by Django 4.0.4 on 2022-08-28 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='news_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='friends'),
        ),
        migrations.AddField(
            model_name='profile',
            name='goals_count',
            field=models.IntegerField(default=0, verbose_name='goals_count'),
        ),
    ]
