# Generated by Django 4.0.4 on 2022-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_remove_profile_news_count_remove_profile_subscribers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False, null=True, verbose_name='active'),
        ),
    ]
