# Generated by Django 4.0.4 on 2022-09-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_profile_friend_offer_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friend_offer',
        ),
    ]
